### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by otsfan203** [N-language/N-#13]
I have created a logo for N#, if you'd like to use it, no credit is required :)

You can find it here: https://u.cubeupload.com/jayfeather/Untitleddrawing2.png

**Comment by BonfireScratch** [comment]
I might use it, thanks!

**Comment by otsfan203** [comment]
> I might use it, thanks!

Thank you!

**Comment by otsfan203** [comment]
> > I might use it, thanks!
> 
> Thank you!

Also, if there's anything you need me to change, I can!

**Comment by BonfireScratch** [comment]
@otsfan203 you don't need to. I have made a lot of logos for the company, I just can't decide which to use

**Comment by otsfan203** [comment]
@BonfireScratch Okay
