### ISSUE TITLE
Variables dictionary not referenced in lexer

### ISSUE THREAD

**Issue by BonfireScratch** [N-language/N-#15]
**Describe the bug**
Variables dictionary not referenced in lexer

**To Reproduce**
1. Enter var x  = 8
2. Enter var y = 0
3. See output
4. Under LEX lies an empty dictionary while under INTER is the correct one

**Expected behavior**
I expected this to happen. What I wanted to happen is to print the same things as the interpreter

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate

**Comment by Dandigit** [comment]
@BonfireScratch Sure! I'll take a look now.

**Comment by BonfireScratch** [comment]
@Dandigit well, if you input a variable name, the lexer will parse it as an identifier, while it's a variable name

**Comment by BonfireScratch** [comment]
@Dandigit you're right. I'll just check in the Interpreter. Let's just close this one
