### ISSUE TITLE
Create a parser

### ISSUE THREAD

**Issue by BonfireScratch** [N-language/N-#17]
Create a parser

**Comment by BonfireScratch** [comment]
@Dandigit @SimpleBinary can you help?

**Comment by otsfan203** [comment]
What exactly are you having trouble with?

**Comment by Dandigit** [comment]
@BonfireScratch I'm assuming you want to decouple the parser and interpreter (which is currently doing the parsing), right?

**Comment by BonfireScratch** [comment]
@Dandigit indeed

**Comment by otsfan203** [comment]
> What exactly are you having trouble with?

**!!**

**Comment by otsfan203** [comment]
@BonfireScratch There are a few questions that I still need answers to. How is N# organized? Does it use bytecode, generate a tree, etc.?

**Comment by BonfireScratch** [comment]
@otsfan203 what are control flow and bytecode?

**Comment by otsfan203** [comment]
@BonfireScratch Control flow is the sequence in which instructions are executed, and bytecode is a method of executing instructions. I need to know both of these things in order to separate the parser (well, I don't know other methods if they exist).

**Comment by BonfireScratch** [comment]
@otsfan203 well, it first lexes the tokens and then checks the tokens one by one.

**Comment by otsfan203** [comment]
@BonfireScratch That's not the answer I'm looking for. How is N# organized? I can't help you unless I know, unfortunately.

**Comment by BonfireScratch** [comment]
@otsfan203 I don't get what you mean...

**Comment by otsfan203** [comment]
@BonfireScratch I need to know **how** the parser and interpreter are coupled, and how it handles control flow. 
You have three choices. The first is not to decouple the parser and interpreter, but I think that it makes sense to make it better organized. The second option is to rewrite the interpreter in an [MCVE](https://stackoverflow.com/help/mcve). The third option is to figure out how N# is organized, and how it handles control flow.
I think I have an example that might be it - is the code executed as the interpreter parses it?

**Comment by BonfireScratch** [comment]
@otsfan203. Yes, indeed.

**Comment by otsfan203** [comment]
@BonfireScratch If that's the case, then if you want to decouple the parser and interpreter you're going to have two options:

1. Make the parser generate an AST, or tree.
2. Make the parser generate Bytecode.

Currently, the interpreter doesn't support control flow so either one of the options above will also allow N# to support control flow.

**Comment by otsfan203** [comment]
woops I pinned this three times

**Comment by BonfireScratch** [comment]
@otsfan203 an AST will be a better option

**Comment by otsfan203** [comment]
Alright! I'm going to close this and make a new discussion about it!
