### ISSUE TITLE
Add more examples, tutorials and create Wiki

### ISSUE THREAD

**Issue by otsfan203** [N-language/N-#20]
**Examples**
The examples folder is meant to contain all sorts of different examples of N# code. However, it only shows Hello World in N#, and I think that adding more examples is necessary and worthwhile.

**Tutorials** 
If N# doesn't publish any tutorials, anyone who wants to start N# wouldn't be able to because there is nothing other than the examples that help you learn N#. It doesn't have a setup tutorial, commands cheatsheet, and all other tutorials that N# needs to be a successful language.

**Comment by otsfan203** [comment]
@BonfireScratch notify

**Comment by BonfireScratch** [comment]
@otsfan203 I definitely agree with you. I would be glad if we created a tutorial website included on the official website, along with some markdown files as well. I am on it right now

**Comment by BonfireScratch** [comment]
@otsfan203 I'm currently looking through a bug I've noticed, so wait until I upload the new code with a better lexer and interpreter. Stay tuned

**Comment by otsfan203** [comment]
@BonfireScratch Confirm my new .nsharp example files

**Comment by otsfan203** [comment]
I think it's safe to close it now. We can add a Wiki and tutorials later - I'll add BinConv when I have time, but let's close this for now.
