### ISSUE TITLE
Interpreter: Generate a Tree

### ISSUE THREAD

**Issue by otsfan203** [N-language/N-#21]
Self-explanatory.

**Comment by otsfan203** [comment]
@Dandigit @BonfireScratch @SimpleBinary Notify

**Comment by BonfireScratch** [comment]
> @Dandigit @BonfireScratch @SimpleBinary Notify

???

**Comment by BonfireScratch** [comment]
@Dandigit how does a parser work?

**Comment by SimpleBinary** [comment]
@BonfireScratch A parser takes your tokens and turns them into an ast.

**Comment by Dandigit** [comment]
@SimpleBinary I think @BonfireScratch was asking how a parser works, not what a parser is, per se.

There's many different parsing techniques around, and people from both industry and academia will try and convince you that their favourite technique is the best. The truth is, parsing really doesn't matter, and any reasonably popular technique should get you by just fine.

I'll define what it actually is that the parser must output: expressions and statements.

**Expressions**
Expressions are the pieces of syntax that express a value. Here are some examples:
```python
23 # Number literal
"foo" # String literal

# Binary operations
40.5 + 23.3
"boo" + "foo"
42 * 1

goo() # Function call: might return a value

variableName # Variables are expressions too
variableName - 40
```
Let's use Python dictionaries to represent AST nodes.
An AST node to represent a number literal expression might look like this:
```python
{
    "type": "NumberLiteral",
    "value": 2
}
```
Number literals are easy to represent, as they are a **terminal node**: they do not reference any other nodes in the tree. A binary operation, however, is **not** a terminal node. Take a look:
```python
2 + 3 + 4
# (is equivalent to)
(2 + 3) + 4
```
Notice how on both sides of the `+`, there's an expression:
```
     NumberLiteral
               |
(2 + 3) + 4
     |
Binary
```
So, the AST node for a binary expression must reference other AST nodes for its left and right operands:
```python
{
    "type": "Binary",
    "operator": "+",

    "left": {
        "type": "Binary",
        "operator": "+",

        "left": {
            "type": "NumberLiteral",
            "value": 2
         },
         "right": {
            "type": "NumberLiteral",
            "value": 3
         },
    },
    "right": {
        "type": "NumberLiteral",
        "value": 4
    }
}
```
You can see that the AST node contains other AST nodes that contain other AST nodes. This is where the "tree" part in Abstract Syntax Tree comes from.

**Statements**
Statements are, to put it simply, pieces of code. Here are some examples of statements:
```
var x = <expression> # Variable declaration

# If statements
if (<expression>) {
   <statements>
}

# Expression statements
<expression> # Maybe a function call? An assignment?
```
An AST node for the variable declaration `var x = 42` may look like this:
```python
{
    "type": "VariableDeclaration",
    "name": "x",
    "initializer": {
        "type": "NumberLiteral",
        "value": 42
    }
}
```
Statements can contain expressions, as seen in the above example. Other types of statements may also contain other statements - like an if statement for example:
```
{
    "type": "IfStatement",
    "condition": {
        "type": "BinaryExpression",
        "operator": "==",

        "left": {
            "type": "NumberLiteral",
            "value": 21
        }
        "right": {
            "type": "NumberLiteral",
            "value": 21
        }
    }

    # A list of statements to represent the body
    "body": [
        {
            "type": "VariableDeclaration",
            "name": "foo",
            "initializer": {
                "type": "StringLiteral",
                 "value": "hello!"
             }
        },
        {
            "type": "PrintStatement",
            "value": {
                 "type": "VariableExpression",
                 "name": "foo"
             }
        },
    ]
}
```
The above AST node would represent the following code:
```
if (21 == 21) {
    var foo = "hello!"
    print foo
}
```

I hope that this has cleared some stuff up for you. Now that you know about ASTs, you can probably Google something like "python recursive descent parser tutorial" for a little tutorial on how to write a parser.

**Comment by BonfireScratch** [comment]
@Dandigit thank you a lot for your time!

**Comment by BonfireScratch** [comment]
@Dandigit I can't get it output the AST for some reason...

**Comment by otsfan203** [comment]
@BonfireScratch Ref?

**Comment by BonfireScratch** [comment]
@otsfan203 I've fixed this on my own

**Comment by otsfan203** [comment]
This is done.

**Comment by BonfireScratch** [comment]
@otsfan203 wait, what?

**Comment by BonfireScratch** [comment]
@otsfan203 it's not done

**Comment by otsfan203** [comment]
@BonfireScratch You said you had resolved it yourself.

**Comment by BonfireScratch** [comment]
@otsfan203 I was talking about the I can't print thing

**Comment by otsfan203** [comment]
@BonfireScratch Oh.

**Comment by BonfireScratch** [comment]
@otsfan203 I am rewriting the entire thing

**Comment by otsfan203** [comment]
@BonfireScratch Okay.

**Comment by BonfireScratch** [comment]
@otsfan203 the rewrite is doing good! It means, however that the syntax will be more
```r
"R-like"
# That's because of R not including the print keyword
# Which means that the print keyword will be removed
```

**Comment by otsfan203** [comment]
@BonfireScratch I'm glad. A bit busy now, March and all, so I won't be very active and able until April.

**Comment by BonfireScratch** [comment]
@otsfan203 do you like the new logo?

**Comment by otsfan203** [comment]
@BonfireScratch Yeah.

**Comment by BonfireScratch** [comment]
@otsfan203 I'll try to change that though. (the syntax, in my rewrite, most of it is nonsense, for testing purposes)

**Comment by BonfireScratch** [comment]
@otsfan203 I have managed to actually put print statements back to the language

**Comment by BonfireScratch** [comment]
@otsfan203 I have added return statements as well
