### ISSUE TITLE
Stick to best practice

### ISSUE THREAD

**Issue by SimpleBinary** [N-language/N-#25]
@BonfireScratch In your code, you seem to use a lot of:
```cpp
using namespace std;
```
This is bad practice and would be better if you just added `std::` before all of your `cout`s and `cin`s.

- SimpleBinary

**Comment by BonfireScratch** [comment]
@SimpleBinary I will do that first when I am able to. Thank you for pointing it out.

**Comment by BonfireScratch** [comment]
@SimpleBinary Do you have any other optimizations to suggest? I would love to hear them.
