### ISSUE TITLE
Get OS version function

### ISSUE THREAD

**Issue by BonfireScratch** [N-language/N-#28]
Just as Python features the `platform.release()` function, N# will feature a variable containing the os version.
We have worked out how to find the os type (eg. Windows, Linux) but it we still have to find a way to retrieve the os release at runtime.

**Comment by BonfireScratch** [comment]
Code for MacOS has been done.

**Comment by BonfireScratch** [comment]
I have found some code that works. It cannot detect Windows 10, however it is the best I could do without external libraries.

**Comment by BonfireScratch** [comment]
@Dandigit since you run Ubuntu, would you mind testing the OS function in your computer?

For your convenience:
```c++
#include <sys/utsname.h>

int main() {
    struct utsname uts;
    uname(&uts);
    std::cout << uts.release;
    return 0;
}
```

**Comment by Dandigit** [comment]
@BonfireScratch I've actually moved over to a Mac, but my server still runs Ubuntu, so you're in luck.

I get this output:
```
4.15.0-76-generic
```
...which I'm fairly sure is my Linux kernel version.

**Comment by BonfireScratch** [comment]
Thank you for your help!

**Comment by Dandigit** [comment]
@BonfireScratch Are you using the `-std=c++17` flag?

**Comment by BonfireScratch** [comment]
@Dandigit Yes.

**Comment by Dandigit** [comment]
@BonfireScratch Can you please post the output from `g++ --version`?

**Comment by BonfireScratch** [comment]
I will when I am able to use the computer (I can use it only once every few days)

**Comment by BonfireScratch** [comment]
@Dandigit by the way, what happened to Yepicsend?

**Comment by BonfireScratch** [comment]
@Dandigit 
```
g++ (MinGW.org GCC-8.2.0-5) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```

**Comment by Dandigit** [comment]
@BonfireScratch That release should definitely support C++17. Are you sure there's no problems with your code?

**Comment by BonfireScratch** [comment]
@Dandigit I am fairly certain. Here are a few of the errors:

```
In file included from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\filesystem:37,
                 from mainClasses.hpp:15,
                 from main.cpp:8:
c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\fs_path.h: In member function 'std::filesystem::__cxx11::path& std::filesystem::__cxx11::path::operator/=(const std::filesystem::__cxx11::path&)':
c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\fs_path.h:237:47: error: no match for 'operator!=' (operand types are 'std::filesystem::__cxx11::path' and 'std::filesystem::__cxx11::path')
    || (__p.has_root_name() && __p.root_name() != root_name()))
```

```
In file included from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\stl_algobase.h:67,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\char_traits.h:39,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\ios:40,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\ostream:38,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\iostream:39,
                 from main.cpp:1:
c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\stl_iterator.h:349:5: note: candidate: 'template<class _IteratorL, class _IteratorR> constexpr bool std::operator!=(const std::reverse_iterator<_Iterator>&, const std::reverse_iterator<_IteratorR>&)'
     operator!=(const reverse_iterator<_IteratorL>& __x,
```

**Comment by BonfireScratch** [comment]
@Dandigit it turns out that the problem is caused by this line:

```c++
#include <filesystem>
```

It actually is a bug in the compiler, and not in my code.

**Comment by Dandigit** [comment]
@Dandigit Perhaps use Clang or MSVC instead? Particularly if you're on Windows, both are much better options (at least in my experience).

**Comment by BonfireScratch** [comment]
@Dandigit I will consider these proposals. Thank you.

**Comment by BonfireScratch** [comment]
@Dandigit https://github.com/N-language/N-/pull/32

**Comment by BonfireScratch** [comment]
@Dandigit #32 could you open the pull request you were talking about?
