### ISSUE TITLE
Consider creating a Discord server

### ISSUE THREAD

**Issue by 7we** [N-language/N-#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Create a community Discord server for this language. Link the invite on the GitHub repository. 

**Describe alternatives you've considered**

**Additional context**
https://discord.com/
Contact me on Discord if you'd like to talk more: 7we#0001

**Comment by BonfireScratch** [comment]
@7we I will see what I can do.

**Comment by BonfireScratch** [comment]
@7we here is the server (it's currently empty). What do you want to be added there?
