### ISSUE TITLE
Can't get value of dictionary variables

### ISSUE THREAD

**Issue by BonfireScratch** [N-language/N-#7]
**Describe the bug**
Can't get value of dictionary variables

**To Reproduce**
1. Run main.py
2. Type something like `var x = 8` and execute
3. Type a random thing and execute
4. Look at the output
5. Find something saying `{}`
6. This should be saying `{"x": 8}`

**Expected behavior**

**Comment by BonfireScratch** [comment]
@otsfan203 @SimpleBinary could you help?

**Comment by otsfan203** [comment]
Hmm... I get this issue as well. I'll try again!

**Comment by SimpleBinary** [comment]
@BonfireScratch I have looked through your code and I think it may be an issue to do with `self.variables` in `varObject.py`.

**Comment by BonfireScratch** [comment]
@SimpleBinary It seems so

**Comment by BonfireScratch** [comment]
@otsfan203 @SimpleBinary I did some testing and I realized that for some reason you cannot even access the dictionary (and variables) in the class itself.

**Comment by SimpleBinary** [comment]
@BonfireScratch I came to the same conclusion.

**Comment by BonfireScratch** [comment]
@Dandigit could you help with this?

**Comment by otsfan203** [comment]
Is it varObject to varObject.py?

**Comment by otsfan203** [comment]
@BonfireScratch So you've already tried that?

**Comment by Dandigit** [comment]
@BonfireScratch Sure!

**Comment by otsfan203** [comment]
@BonfireScratch I'm confused. I asked if it was varObject to varObject.py, and your answer was 'yes'. Have you tried it already, or are looking for usages?

**Comment by Dandigit** [comment]
Merge #8 to fix.
